[project_definition]
binary_path = "./main"
makefile_path = "."
make_targets = [ "all"]
project_name = "main"
global_timeout = 20

[[testcases]]
name = "first testcase"
description = "no description"
type = "OrdIO"
io_file = "./tests/01/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0
